version: '3.9'

services:
  backend:
    restart: always
    container_name: api
    build: ./api
    ports:
      - 4000:4000
  frontend:
    restart: always
    container_name: frond
    build: ./client
    ports:
      - 3000:80
    depends_on:
      - backend
    